### PR TITLE
Added missing package dependencies

### PR DESCRIPTION
**Pull request by btpoe**
and ensure node_modules is not commited to git

### CODE REVIEW

**Comment by maluramichael** [comment]
Is it cool to have react and react-native as a dependency? I tried to use them as peerDependencies because i saw many other modules break the code because the included their own version of react and react-native.

**Comment by btpoe** [comment]
It depends on what version of npm you are using. v3 deprecates peerDependencies. I think they've done a better job of resolving dependencies between modules in v3, so I'm not sure how big of an impact you'll see between the two options.

**Comment by maluramichael** [comment]
Ok then lets do a compromise :D let react and react-native as a dependency but set the versions to      "react": "^15.3.1", "react-native": "^0.32.0"

**Comment by btpoe** [comment]
The react version shouldn't be an issue, but as far as the react-native version, I believe when a npm module is at a 0.x version, npm will not resolve a higher minor version number. Let me look into that and confirm.

**Pull request merged**
